UMS/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UMS.Models;

namespace UMS.Controllers
{
    public class CourseController : Controller
    {
        ProjectDBContext db = new ProjectDBContext();
        //
        // GET: /Course/
        public ActionResult Index()
        {
            var courses = db.Courses.Include(c => c.Department).Include(c => c.Semester);
            return View(courses.ToList());
        }
        
        //
        // GET: /Course/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code");
            ViewBag.SemesterId = new SelectList(db.Semesters, "SemesterId", "Name");
            return View();
        }

        //
        // POST: /Course/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CourseId,Code,Name,Credit,Description,DepartmentId,SemesterId")] Course course)
        {
            course.Status = true;
            var list = from p in db.Semesters where p.SemesterId == course.SemesterId select p;
            foreach (var item in list)
            {
                course.SemName = item.Name;
            }
            if (ModelState.IsValid)
            {
                if (!course.IsExistCode(course.Code)) 
                {
                    if (!course.IsExistName(course.Name))
                    {
                        db.Courses.Add(course);
                        db.SaveChanges();
                        TempData["Success"] = "Added Successfully!!";
                        return RedirectToAction("Create");
                    }
                    else
                    {
                        ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                        ViewBag.SemesterId = new SelectList(db.Semesters, "SemesterId", "Name", course.SemesterId);
                        ViewBag.NameMessage = "Course Name Already Exist";
                        return View();
                    }
                }
                else
                {
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.SemesterId = new SelectList(db.Semesters, "SemesterId", "Name", course.SemesterId);
                    ViewBag.Message = "Course code already Exist.";
                    return View(); 
                }
                
            }

            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
            ViewBag.SemesterId = new SelectList(db.Semesters, "SemesterId", "Name", course.SemesterId);
            return View(course);
        }
    }
}

UMS/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UMS.Models;

namespace UMS.Controllers
{
    public class DepartmentController : Controller
    {
        ProjectDBContext db = new ProjectDBContext();
        //
        // GET: /Department/
        public ActionResult Index()
        {
            List<Department> departments = db.Departments.OrderBy(x => x.Name).ToList();
            return View(departments);
        }

        //
        // GET: /Department/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Department/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Department department)
        {
            if (ModelState.IsValid)
            {
                if (!department.IsExistCode(department.Code)) 
                {
                    if (!department.IsExistName(department.Name))
                    {
                        db.Entry(department).State = EntityState.Added;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.NameMessage = "Department Name Already Exist.";
                        return View();
                    }
                }
                else
                {
                    ViewBag.CodeMessage = "Department Code already Exist.";
                    return View(); 
                }
            }
            else
            {
                return View(department);
            }
        }
    }
}

UMS/Controllers/RoomAllocationController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UMS.Models;

namespace UMS.Controllers
{
    public class RoomAllocationController : Controller
    {
        ProjectDBContext db = new ProjectDBContext();
        public ActionResult UnallocateClassRooms(string submit)
        {
            if (submit == "Unallocate Rooms")
            {
                var rooms = from p in db.RoomAllocations where p.Status.Equals(true) select p;
                foreach (var roomAllocation in rooms)
                {
                    roomAllocation.Status = false;
                    //db.RoomAllocations.AddOrUpdate(roomAllocation);
                    db.Entry(roomAllocation).State = EntityState.Modified;
                    
                }
                db.SaveChanges();
                ViewBag.message = "Sucessfully Unallocated All Class Rooms";

            }
            return View();
        }
        //public string UnallocateClassRooms()
        //{
        //    var rooms = from p in db.RoomAllocations where p.Status.Equals(true) select p;
        //    foreach (var roomAllocation in rooms)
        //    {
        //        roomAllocation.Status = false;
        //        db.RoomAllocations.AddOrUpdate(roomAllocation);
        //    }
        //    db.SaveChanges();
        //    return "Sucessfully Unallocated All Class Rooms";
        //}
       
        //
        // GET: /RoomAllocation/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId","Code");
            ViewBag.CourseId = new SelectList("", "CourseId","Code");
            ViewBag.RoomId = new SelectList(db.Rooms, "RoomId","Name");
            ViewBag.DayId = new SelectList(db.Days, "DayId","Name");

            return View();
        }

        //
        // POST: /RoomAllocation/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoomAllocation roomAllocation)
        {
            Room room = db.Rooms.Find(roomAllocation.RoomId);
            Course course = db.Courses.Find(roomAllocation.CourseId);
            Day day = db.Days.Find(roomAllocation.DayId);
            roomAllocation.Status = true;

            if (ModelState.IsValid)
            {
                int from, end;
                try
                {
                    from = ConvertTimetoInt(roomAllocation.From);
                }
                catch (Exception x)
                {
                    if (TempData["ErrorMessage"] == null)
                    {
                        TempData["ErrorMessage1"] = x.Message;
                    }
                    TempData["ErrorMessage2"] = TempData["ErrorMessage"];
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomAllocation.CourseId);
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomAllocation.RoomId);
                    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomAllocation.DayId);
                    return View(roomAllocation);
                }
                try
                {
                    end = ConvertTimetoInt(roomAllocation.To);
                }
                catch (Exception anException)
                {
                    if (TempData["ErrorMessage3"] == null)
                    {
                        TempData["ErrorMessage2"] = anException.Message;
                    }
                    TempData["ErrorMessage5"] = TempData["ErrorMessage3"];
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomAllocation.CourseId);
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomAllocation.RoomId);
                    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomAllocation.DayId);
                    return View(roomAllocation);
                }
                if (end < from)
                {
                    TempData["Error"] = "Class Must Should be Started at 24 hours";
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomAllocation.CourseId);
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomAllocation.RoomId);
                    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomAllocation.DayId);
                    return View(roomAllocation);
                }
                if (end == from)
                {
                    TempData["Error"] = "Class Must Should be Started at 24 hours";
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomAllocation.CourseId);
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomAllocation.RoomId);
                    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomAllocation.DayId);
                    return View(roomAllocation);
                }
                if ((from < 0) || (end >= (24 * 60)))
                {
                    TempData["Message"] = " 24 hours--format HH:MM";
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomAllocation.CourseId);
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomAllocation.RoomId);
                    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomAllocation.DayId);
                    return View(roomAllocation);
                }
                List<RoomAllocation> OverLabs = new List<RoomAllocation>();

                var DayRoomAllocationList =
                    db.RoomAllocations.Include(c => c.Course)
                        .Include(d => d.Day)
                        .Include(r => r.Room)
                        .Where(r => r.RoomId == roomAllocation.RoomId && r.DayId == roomAllocation.DayId)
                        .ToList();
                foreach (var aDayroomAllocation in DayRoomAllocationList)
                {
                    if (aDayroomAllocation.Status.Equals(true))
                    {
                        int DbFrom = ConvertTimetoInt(aDayroomAllocation.From);
                        int DbEnd = ConvertTimetoInt(aDayroomAllocation.To);

                        if (
                                ((DbFrom <= from) && (from < DbEnd))
                                || ((DbFrom < end) && (end <= DbEnd))
                                || ((from <= DbFrom) && (DbEnd <= end))
                            )
                        {
                            OverLabs.Add(aDayroomAllocation);
                        }
                    }
                }
                if (OverLabs.Count == 0)
                {

                    db.RoomAllocations.Add(roomAllocation);
                    db.SaveChanges();
                    TempData["Message"] ="Successfull Allocated!!"+ "Room : " + room.Name + " " + "Allocated "
                    + " for course : " + course.Code + " From " + roomAllocation.From
                    + " to " + roomAllocation.To + " on " + day.Name;
                }
                else
                {
                    string message = "Room : " + room.Name ;
                    foreach (var anOverlappedRoom in OverLabs)
                    {
                        int dbFrom = ConvertTimetoInt(anOverlappedRoom.From);
                        int dbEnd = ConvertTimetoInt(anOverlappedRoom.To);

                        string overlapStart, overlapEnd;

                        if ((dbFrom <= from) && (from < dbEnd))
                            overlapStart = roomAllocation.From;
                        else
                            overlapStart = anOverlappedRoom.From;

                        if ((dbFrom < end) && (end <= dbEnd))
                            overlapEnd = roomAllocation.To;
                        else
                            overlapEnd = anOverlappedRoom.To;
                        message += " Course : " + anOverlappedRoom.Course.Code  + " Overlapped from : ";
                        message += overlapStart + " To " + overlapEnd;
                    }

                    TempData["Overlapping"] = message + " on " + day.Name;

                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code");
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomAllocation.CourseId);
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomAllocation.RoomId);
                    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomAllocation.DayId);
                    return View(roomAllocation);
                }
                return RedirectToAction("Create");
            }

UMS/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UMS.Models;

namespace UMS.Controllers
{
    public class StudentController : Controller
    {
        ProjectDBContext db = new ProjectDBContext();
        //
        // GET: /Student/
        public ActionResult Index()
        {
            var students = db.Students.Include(s => s.Department);
            return View(students.ToList());
        }

        //
        // GET: /Student/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        //
        // GET: /Student/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code");
            return View();
        }

        //
        // POST: /Student/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentId,Name,Email,ContactNo,Date,Address,DepartmentId,RegistrationId")] Student student)
        {
            if (ModelState.IsValid)
            {
                if (!student.IsExist(student.Email))
                {
                    student.RegistrationId = GenerateRegistrationId(student);

                    db.Students.Add(student);
                    db.SaveChanges();
                    TempData["reg"] = student.Name + ". RegistrationId is : " + student.Name;
                    ViewBag.RegId = student.Name + ". RegistrationId is : " + student.Name;
                    TempData["Success"] = "Registration Successfull";
                    return RedirectToAction("Create");
                    //return RedirectToAction("Details", new { id = student.StudentId });
                }
                else
                {
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DepartmentCode", student.DepartmentId);
                    ViewBag.Message = "Email already Exist.";
                    return View();
                }
                
            }
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DepartmentCode", student.DepartmentId);
            return View(student);
        }

        private string GenerateRegistrationId(Student student)
        {
            int id =
                db.Students.Count(s => (s.DepartmentId == student.DepartmentId) && (s.Date.Year == student.Date.Year)) + 1;
            Department department = db.Departments.FirstOrDefault(d => d.DepartmentId == student.DepartmentId);
            string registrationId = department.Code + "-" + student.Date.Year + "-";
            
            return registrationId + id.ToString("000");
        }

    }
}

UMS/Views/Shared/_CourseInfo.cshtml
<div id="CourseInfo">
    <div class="form-group">
        @Html.Label("Course Code :", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @ViewBag.Code
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Credit  :", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @ViewBag.Credit
        </div>
    </div>
</div>

UMS/Views/Shared/_CourseStatus.cshtml
@model IEnumerable<UMS.Models.Course>

@if (Model != null)
{
    <div class="form-horizontal">
        <hr />
        <table class="table table-striped text-center">
            <h3>Course Information</h3>
            <tr>
                <th style="text-align: center;">
                    Course code
                </th>
                <th style="text-align: center;">
                    Course Name
                </th>
                <th style="text-align: center;">
                    Semester
                </th>
                <th style="text-align: center;">
                    Assigned To
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SemName)
                    </td>
                    <td>
                        @if (item.AssignTo != null)
                        {
                            @Html.DisplayFor(modelItem => item.AssignTo)
                        }
                        @if (item.AssignTo == null)
                        {
                            item.AssignTo = "Not Assigned Yet";
                            @Html.DisplayFor(modelItem => item.AssignTo)
                        }
                    </td>

                </tr>
            }

        </table>
        </div>
}
<div style="color: darkgoldenrod"><h3>@ViewBag.NotAssigned</h3></div>

UMS/Views/Shared/_FillteredTeacher.cshtml
@if (ViewBag.TeacherId != null)
{
    @Html.DropDownList("TeacherId", string.Empty)

}

UMS/Views/Shared/_FilteredCourse.cshtml
@if (ViewBag.CourseId != null)
{
    @Html.DropDownList("CourseId", string.Empty)
}

UMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("University Course and Result Management System", "Index", "Home", null, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-left">
                        @*<li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Department <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Save Department","Create","Department")</li>
                                <li>@Html.ActionLink("View All Department","Index","Department")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Course <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Save Course", "Create", "Course")</li>
                                <li>@Html.ActionLink("Course Assign to Teacher","Create","AssignCourse")</li>
                                <li>@Html.ActionLink("View Course Statics","ViewCourseStatus","AssignCourse")</li>
                                <li>@Html.ActionLink("Enroll In a Course","Create","EnrollCourse")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Teacher <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Save Teacher", "Create", "Teacher")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Student <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Register Student", "Create", "Student")</li>
                                <li>@Html.ActionLink("Save Student Result","Create","ResultEntry")</li>
                                <li>@Html.ActionLink("View Result","ViewResult","ResultEntry")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Class Rooms <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Allocate Classrooms", "Create", "RoomAllocation")</li>
                                <li>@Html.ActionLink("View Class Schedule and Room Allocation Information", "RoomAllocationView", "RoomAllocation")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Unassing OR Unallocate <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Unassign All Courses", "UnassignCourses", "AssignCourse")</li>
                                <li>@Html.ActionLink("Unallocate All Class Rooms", "UnallocateClassRooms", "RoomAllocation")</li>
                            </ul>
                        </li>
                    </ul>
                </div>
            
                
            
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Be Lazy</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>

UMS/Views/Shared/_ResultInformation.cshtml
@model IEnumerable<UMS.Models.EnrollCourse>

@if (Model != null)
{
    <table class="table table-striped text-center">
        <tr>
            <th style="text-align: center;">
                Course Code
            </th>
            <th style="text-align: center;">
                Name
            </th>
            <th style="text-align: center;">
                Grade
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Course.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course.Name)
                </td>
                <td>
                    @if (item.GradeName != null)
                    {
                        @Html.DisplayFor(modelItem => item.GradeName)
                    }
                    @if (item.GradeName == null)
                    {
                        item.GradeName = "Not Assigned";
                        @Html.DisplayFor(modelItem => item.GradeName)
                    }

                </td>
            </tr>
        }
    </table>
}
<div style="color: darkgoldenrod"><h3>@ViewBag.NotEnrolled</h3></div>

UMS/Views/Shared/_RoomAllocationView.cshtml
@model IEnumerable<UMS.Models.Course>
<table class="table table-striped text-center">
    <tr>
        <th style="text-align: center;">
            Course Code
        </th>
        <th style="text-align: center;">
            Name
        </th>
        <th style="text-align: center;">
            Schedule Info
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @foreach (var anAllocatedRoom in item.RoomAllocationList)
                {
                    <b>Room:</b>
                    @Html.DisplayFor(modelItem => anAllocatedRoom.Room.Name)
                    <i>,</i>
                    @Html.DisplayFor(modelItem => anAllocatedRoom.Day.Name)
                    <i>,</i>
                    @Html.DisplayFor(modelItem => anAllocatedRoom.From)
                    <i>-</i>
                    @Html.DisplayFor(modelItem => anAllocatedRoom.To)
                    <b><i>;</i></b>
                }
                @if (item.RoomAllocationList.Count == 0)
                {
                    <i>Not Scheduled Yet</i>
                }
            </td>
        </tr>
    }
</table>
<div style="color: darkgoldenrod"><h3>@ViewBag.NoCourse</h3></div>

UMS/Views/Shared/_StudentInformation.cshtml
<div id="StudentInfo">
    <div class="form-group">
        @Html.Label("Name :", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @ViewBag.Name
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Email : ", new {@class="control-label col-md-2"})
        <div class="col-md-10">
            @ViewBag.Email
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Department : ", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @ViewBag.Dept
        </div>
    </div>
</div>

UMS/Views/Shared/_TeachersCreditInfo.cshtml
<div id="TeacherInfo">
    <div class="form-group">
        @Html.Label("Credit to be taken :", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @ViewBag.Credit
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Remaining Credit  :", new {@class="control-label col-md-2"})
        <div class="col-md-10">
            @ViewBag.RemainingCredit
        </div>
    </div>
</div>